# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: ACE
  vmImage: DESKTOP-0GBF6M5

stages:
  - stage: Build
    displayName: Build Stage
    environment: 'digital-dev'
    jobs:
      - job: ACEBuild
        displayName: ACE Build and Publish artifacts
        steps:
        - task: gitversion/setup@0
          displayName: Setup GitVersion
          inputs:
            versionSpec: '5.*'
        - task: gitversion/execute@0
          displayName: Execute GitVersion
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/Test'
            useConfigFile: true
            configFilePath: './GitVersion.yml'
          condition: contains(variables['build.SourceBranch'],'main')
